import React, { useState, useEffect } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import styles from './home.module.scss';
const Home = () => {
  return (
    <div className='text-white'>
      <div className='container mb-4'>
        <h2 className='text-left'><br/><br/>1. Các khái niệm cơ bản</h2>
        <p className={styles.justify}>Quản lý Hiện nay có rất nhiều quan niệm khác nhau về quản lý [2]. Theo tác giả bài viết, mỗi quan niệm đều có thể được chấp nhận khi ta xem xét quan niệm đó được nhìn nhận ở góc độ nào. Vì vậy, nghiên cứu các quan niệm về quản lý, tác giả nghiêng về quan niệm quản lý của các nhà kinh điển cho rằng, quản lý xuất hiện với vai trò là người tổ chức và điều khiển những người khác khi họ cùng tham gia thực hiện một hoạt động nhất định. Ở đây có thể hiểu, người tổ chức và điều khiển (một hoặc một số người) là chủ thể quản lý và những người khác trong mối quan hệ này được coi là đối tượng quản lý. Từ đây tác giả định nghĩa: Quản lý là hoạt động có mục đích của chủ thể quản lý hướng tới đối tượng quản lý nhằm tổ chức và điều hành mọi hoạt động của đối tượng quản lý để thực hiện mục tiêu mà chủ thể quản lý đặt ra.</p>
        <h2>Quản lý thư viện</h2>
        <p className={styles.justify}>Trong một số tài liệu chuyên môn về thư viện đã có các định nghĩa về quản lý thư viện (QLTV) như sau:
          <br/>- Là sự tác động có chủ đích tới tập thể người lao động để tổ chức và phối hợp hoạt động của họ trong quá trình thực hiện các mục đích và nhiệm vụ đề ra. QLTV dựa trên quyền hạn được quy định và cùng với nó là sự tác động tổ chức, điều hành [1].
          <br/>- Là hoạt động được các cán bộ lãnh đạo và tập thể viên chức thực hiện một cách tự giác và có kế hoạch nhằm đảm bảo cho sự hoạt động và phát triển bình thường của thư viện, bao gồm: kế hoạch, tổ chức và kích thích lao động, quản lý các quá trình thư viện, thống kê và kiểm tra công việc, công tác cán bộ (tổ chức cán bộ) [7].
          <br/>Tổng hợp những định nghĩa nêu trên, tác giả cho rằng QLTV là quản lý 3 lĩnh vực: quản lý con người, quản lý chuyên môn và quản lý cơ sở vật chất của thư viện. Và vì 3 lĩnh vực này  được quản lý bằng con người và thông qua con người, nên có thể định nghĩa QLTV như sau:
          Là sự tác động có mục đích của chủ thể quản lý thư viện (cá nhân, tập thể) lên đối tượng quản lý (tập thể công chức, viên chức của thư viện) với mục đích tổ chức và điều hành hoạt động của họ nhằm đạt được mục tiêu mà chủ thể quản lý đề ra.</p>
        <h2>Quản lý thư viện hiện đại</h2>
        <p className={styles.justify}>Thư viện hiện đại là một loại thư viện được áp dụng những thành tựu mới nhất của khoa học kỹ thuật mà cụ thể là công nghệ thông tin (CNTT). Dưới tác động của ứng dụng CNTT, thư viện hiện đại có rất nhiều thay đổi: từ cơ cấu tổ chức, nguồn nhân lực cho đến cơ sở vật chất trang thiết bị [6]. Tuỳ thuộc vào mức độ ứng dụng CNTT vào hoạt động của thư viện mà người ta xây dựng thư viện hiện đại với các cấp độ khác nhau và tương ứng với chúng là những tên gọi khác nhau như: thư viện đa phương tiện, thư viện lai, thư viện điện tử , thư viện số, thư viện ảo… Nói một cách khác, nhắc đến tên các thư viện này thì ta đều hiểu chúng là các thư viện hiện đại. Ví dụ, thư viện đa phương tiện hay thư viện lai là thư viện hiện đại ở mức độ sơ khai được chuyển tiếp từ thư viện truyền thống sang thư viện có ứng dụng CNTT. Trong thư viện này vừa tồn tại tài liệu truyền thống vừa có các dạng tài liệu hiện đại. Hay thư viện số là thư viện hiện đại ở cấp độ cao hơn. Trong thư viện này không còn tài liệu dạng truyền thống mà chúng đã được số hoá và được sử dụng bằng máy tính, phương tiện truyền thông
          <br/>Bởi vậy, khi nói đến QLTV hiện đại là nói đến việc quản lý tất cả các dạng thư viện như đã nêu bao gồm: thư viện đa phương tiện, thư viện lai, thư viện số, thư viện ảo… Nói một cách khác, khi nói đến quản lý một trong các dạng thư viện này thì về bản chất đều là QLTV hiện đại.
          <br/>Vậy QLTV hiện đại là gì? QLTV hiện đại có khác gì so với QLTV truyền thống? Theo tác giả để định nghĩa được QLTV hiện đại cần phân biệt các điểm giống và khác nhau giữa QLTV truyền thống và QLTV hiện đại.
          <br/>- Những điểm giống nhau:
          <br/>Thứ nhất, chủ thể quản lý và đối tượng quản lý đều là con người. Bởi ngoài đối tượng quản lý là con người thì hoạt động chuyên môn và các hoạt động khác được coi là các đối tượng của quản lý thì đều do con người và bằng chính con người thực hiện.
          <br/>Thứ hai, nội dung quản lý như nhau bao gồm: quản lý nguồn nhân lực, quản lý hoạt động chuyên môn, các hoạt động khác và cơ sở vật chất, kinh phí của thư viện.
          <br/>Thứ ba, quản lý cả 2 loại thư viện đều phải sử dụng các chức năng, nguyên tắc, phương pháp và công cụ quản lý.
          <br/>- Những điểm khác nhau:
          <br/>Thứ nhất, phương pháp tổ chức - hành chính của quản lý: Trong thư viện truyền thống sự tác động của người quản lý tới tập thể công chức, viên chức được thực hiện bằng các mệnh lệnh, quyết định buộc người bị quản lý phải phục tùng. Trong thư viện hiện đại sự tác động của người quản lý tới tập thể công chức, viên chức cũng được thực hiện bằng các mệnh lệnh, quyết định nhưng có sự tham gia của người dưới quyền.
          <br/>Thứ hai, công cụ quản lý: Trong thư viện truyền thống người quản lý sử dụng công cụ thủ công để quản lý như: ghi chép, đo, đếm. Chẳng hạn dùng các bảng, biểu theo dõi, tự theo dõi và đồng hồ để quản lý giờ giấc và sản phẩm theo định mức lao động hoặc dùng các bản báo cáo để đánh giá các loại công việc và khối lượng công việc đã được hoàn thành… Trong thư viện hiện đại người quản lý sử dụng công cụ hiện đại như máy tính, phần mềm quản lý, camera… để quản lý.
          <br/>Thứ ba, trình độ quản lý: Để QLTV truyền thống cũng như hiện đại, đối với người quản lý ngoài những đòi hỏi đầy đủ về phẩm chất đạo đức, phẩm chất chuyên môn, đòi hỏi về trình độ và kỹ năng quản lý. Cụ thể, trong thư viện truyền thống người quản lý một mặt phải hiểu biết về các chức năng, nguyên tắc, phương pháp và công cụ quản lý. Mặt khác, phải biết vận  dụng tốt các chức năng, nguyên tắc, phương pháp và công cụ quản lý đó. Đồng thời, phải có các kỹ năng giao tiếp, làm việc nhóm, kỹ năng nhận thức và giải quyết nhanh chóng các tình huống có vấn đề… Trong thư viện hiện đại, bên cạnh những kiến thức và kỹ năng trên, đối với người quản lý còn đòi hỏi các kiến thức về ứng dụng CNTT vào hoạt động thư viện và đặc biệt là kỹ năng thực hành phần mềm quản lý thành thạo.
          <br/>Từ những điều trình bày trên cho thấy, về bản chất QLTV truyền thống và QLTV hiện đại là quản lý con người. Bởi trong các thư viện hiện đại vẫn cần có sự hiện diện của con người để tổ chức và điều hành các hoạt động của thư viện. Điều khác biệt là người quản lý tác động lên đối tượng quản lý không chỉ theo một chiều từ trên xuống mà người quản lý còn phải tiếp nhận sự phản hồi từ đối tượng quản lý (từ dưới lên) và khi thực hiện hoạt động quản lý thì sử dụng các phương tiện kỹ thuật để hỗ trợ. Từ đây có thể định nghĩa QLTV hiện đại như sau:
          <br/>Là hoạt động được chủ thể quản lý và đối tượng quản lý tự giác thực hiện nhằm đảm bảo đạt được mục tiêu của thư viện với sự hỗ trợ của các phương tiện kỹ thuật hiện đại.</p>
      </div>
      <h2>2. Khái quát một số nội dung quản lý thư viện hiện đại</h2>
      <p className={styles.justify}><b>Quản lý nguồn nhân lực thư viện</b>
        <br/>Quản lý nguồn nhân lực trong thư viện chính là tổ chức và điều hành hiệu quả tập thể công chức, viên chức thư viện trên cơ sở tạo điều kiện làm việc thuận lợi cũng như đáp ứng nhu cầu vật chất và tinh thần ngày càng cao cho họ.
        <br/>Trong điều kiện thư viện hiện đại, vừa phải thực hiện các khâu công việc truyền thống vừa phải thực hiện các khâu công việc hiện đại thì vấn đề đảm bảo số lượng và chất lượng nguồn nhân lực phải được quan tâm hàng đầu, nhất là vấn đề chất lượng. Chính vì vậy, muốn quản lý nguồn nhân lực thư viện tốt cần đảm bảo thực hiện tốt các chức năng, nguyên tắc và phương pháp quản lý nguồn nhân lực.
        <br/>Các chức năng quản lý nguồn nhân lực bao gồm: tuyển dụng; bố trí, sử dụng; đào tạo và phát triển. Nhiệm vụ của tuyển dụng là vừa phải đảm bảo đủ số lượng với các phẩm chất chuyên môn phù hợp đáp ứng yêu cầu của công việc vừa phải tuân thủ theo pháp lệnh công chức và theo quy định cụ thể của từng cơ quan. Nhiệm vụ của sử dụng nguồn nhân lực là bố trí, sắp xếp công việc hợp lý, phù hợp năng lực, sở trường của công chức, viên chức. Nhiệm vụ của đào tạo và phát triển nguồn nhân lực là phải chú trọng nội dung đào tạo, bồi dưỡng về lý luận chính trị, về quản lý, chuyên môn, ngoại ngữ và tin học, cũng như phát triển về nhân cách và thể lực [4,5].
        <br/>Các nguyên tắc mà quản lý nguồn nhân lực cần tuân thủ bao gồm:
        <br/>- Các chủ trương, chính sách quản lý phải nhằm vào việc thoả mãn nhu cầu vật chất và tinh thần cho tập thể người lao động.
        <br/>- Đầu tư thích đáng cho đào tạo, phát triển nguồn nhân lực.
        <br/>- Quản lý nguồn nhân lực phải được coi là chức năng của tất cả các nhà quản lý trực tiếp.
        <br/>Các phương pháp quản lý nguồn nhân lực bao gồm: Phương pháp tổ chức - hành chính, tâm lý - giáo dục và kinh tế. Để các phương pháp này tác động tới nguồn nhân lực thư viện có hiệu quả, một mặt cần được thực hiện đồng bộ và mềm dẻo, uyển chuyển. Mặt khác phải đảm bảo mọi người đều được tham gia vào quản lý, coi hoạt động quản lý là hoạt động tự giác cần phải được tất cả mọi người thực hiện nhằm đạt được mục tiêu chung mà thư viện đặt ra [3].</p>
    </div>
  );
}

export default Home;